// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VistoriaAPI.Data;

#nullable disable

namespace VistoriaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240628014329_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("VistoriaAPI.Veiculos.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano_Fabricacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano_Modelo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chassi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataIntegracao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Linha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Potencia")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Placa", "Chassi", "Motor");

                    b.ToTable("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
